# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  test:
    docker:
      - image: node:14
     steps:
      - checkout
      -run:
        name: "Install node packages"
        command: npm run test
workflows:
  project-workflow:
    jobs:
      - test
